## Упражнения по библиотеке Numpy

In [ ]:
import math
import random

import numpy as np
from debugpy.common.timestamp import current
from pandas.core.dtypes.missing import array_equals

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
# your code
arr = np.arange(0, 10)
print(arr)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
# your code
arr = np.random.random(10)
print(f'Initial array: {arr}')
print(f'Max element: {arr.max()}, it\'s index: {arr.argmax()}')
arr[arr.argmax()] = 0
print(f'Final array: {arr}')


Initial array: [0.65285057 0.02289248 0.60903279 0.88239008 0.97589029 0.59456455
 0.5440397  0.87611476 0.18388719 0.28861613]
Max element: 0.9758902856027728, it's index: 4
Final array: [0.65285057 0.02289248 0.60903279 0.88239008 0.         0.59456455
 0.5440397  0.87611476 0.18388719 0.28861613]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
arr = np.array([[1,2], [3,4]])
print(f'Initial matrix: {arr}\n')
x, y = arr[0], arr[1]
res = (np.array(np.meshgrid(x, y, indexing='ij')))
print(res, '\n')
res = res.T
print(res, '\n')
res = res.reshape(-1, 2)
print(res, '\n')

Initial matrix: [[1 2]
 [3 4]]

[[[1 1]
  [2 2]]

 [[3 4]
  [3 4]]] 

[[[1 3]
  [2 3]]

 [[1 4]
  [2 4]]] 

[[1 3]
 [2 3]
 [1 4]
 [2 4]] 



**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
# your code
np.random.seed(123)
A = np.random.randint(0, 10, size=(8, 3))
B = np.random.randint(0, 10, size=(2, 2))
res = A[np.isin(A, B[0]).any(axis=1) & np.isin(A, B[1]).any(axis=1)]
res

array([[4, 1, 7],
       [3, 2, 4]])

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
# your code
arr = np.random.randint(0, 2, size=(10, 3))
arr.sort(axis=1)
mask = np.where(arr[:, 0] != arr[:, -1])
arr[mask]

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [0, 0, 1]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
# your code
arr = np.array(
    [
        [1, 2, 3],
        [1, 2, 4],
        [1, 2, 3],
        [3, 4, 5]
    ]
)
np.unique(arr, axis=0)

array([[1, 2, 3],
       [1, 2, 4],
       [3, 4, 5]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [8]:
# python implementation
x = [
        [1, 0, 1],
        [2, 0, 2],
        [3, 0, 3],
        [4, 4, 4]
]
mul = 1
for i in range(len(x[0])):
    mul *= x[i][i] if x[i][i] != 0 else 1

mul

3

In [9]:
# numpy
x = np.array(
    [
        [1, 0, 1],
        [2, 0, 2],
        [3, 0, 3],
        [4, 4, 4]
])
mul = np.prod(np.diag(x)[np.diag(x) != 0])
mul

np.int64(3)

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
# python
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
res = True if sorted(x) == sorted(y) else False
res

True

In [11]:
# numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
np.array_equal(np.sort(x), np.sort(y))

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [12]:
# python
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
bigest_num = None
for i in range(1, len(x)):
    if x[i-1] == 0:
        bigest_num = x[i]

print(bigest_num)

5


In [13]:
# numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
nulls_indx = np.where(x == 0)[0]
nums_indx = nulls_indx + 1
nums_indx = nums_indx[nums_indx < len(x)]
np.max(x[nums_indx])

np.int64(5)

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [14]:
# python
x = [2, 2, 2, 3, 3, 3, 5]
x = sorted(x)
nums = []
count = []
n = x[0]
c = 0
for i in x:
    if i == n:
        c += 1
    else:
        nums.append(n)
        count.append(c)
        n = i
        c = 1
nums.append(n)
count.append(c)

print(nums, count)

[2, 3, 5] [3, 3, 1]


In [15]:
# numpy
x = np.array([1, 2, 2, 2, 3, 3, 3, 5])
res = np.unique(x, return_counts=True)
res

(array([1, 2, 3, 5]), array([1, 3, 3, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [18]:
import random
from scipy.spatial.distance import cdist

In [28]:
%time
random.seed(123)
n, m, dims = 100, 100, 10
X = [[random.random() for _ in range(dims)] for _ in range(n)]
Y = [[random.random() for _ in range(dims)] for _ in range(m)]

res = [[0 for _ in range(m)] for _ in range(n)]

for i in range(n):
    for j in range(m):
        s = sum((x - y)**2 for x, y in zip(X[i], Y[j]))
        res[i][j] = s**0.5

res[0][0]


CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 3.1 μs


1.439724279759413

In [29]:
%time
# fancy func
X = np.array(X)
Y = np.array(Y)
res = cdist(X, Y, metric='euclidean')
res

CPU times: user 1 μs, sys: 1 μs, total: 2 μs
Wall time: 3.1 μs


array([[1.43972428, 1.39691906, 1.22741669, ..., 1.47326447, 1.55203086,
        1.35074574],
       [1.55304988, 1.46926353, 1.1898577 , ..., 1.55274077, 1.47261678,
        1.55125627],
       [1.62882084, 1.40523037, 1.28101151, ..., 1.63674634, 1.23755387,
        1.60149562],
       ...,
       [1.09094535, 1.07928529, 1.1297249 , ..., 1.2476284 , 1.16143321,
        1.19679581],
       [1.37603689, 1.22162929, 1.20697729, ..., 1.38819122, 0.8677861 ,
        0.93525732],
       [1.56709408, 1.11875274, 0.94945842, ..., 1.5820319 , 1.44214014,
        1.67353735]], shape=(100, 100))

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [30]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [36]:
# your code
average_calories = np.average(calorie_stats)
print(f'Average calories from other companies: {average_calories},'
      f'\nGap to calories in our cereals: {average_calories - 60}')

Average calories from other companies: 106.88311688311688,
Gap to calories in our cereals: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [38]:
# your code
calories_stats_sorted = np.sort(calorie_stats)
calories_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [41]:
# your code
median_calories = np.median(calorie_stats)
median_calories

np.float64(110.0)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [51]:
# your code
nth_percentile = 0
for p in range(1, 101):
    current_percentile = np.percentile(calorie_stats, p)

    if current_percentile > 60:
        nth_percentile = p
        break
nth_percentile

4

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [54]:
# your code
more_calories = len(calorie_stats[calorie_stats > 60])/len(calorie_stats)
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [55]:
# your code
calorie_std = np.std(calorie_stats)
calorie_std

np.float64(19.35718533390827)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Проведённый анализ показывает, что CrunchieMunchies имеют калорийность ниже среднех и медианных значений по рынку, а также что они находятся в нижнем процентиле среди конкурентов. Можно сделать ставку во время рекламы на "здоровость" продукта и что он подходит для тех, кто следит за калориями и своим питанием.